name: Build and Deploy GeminiSpot Flasher

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v4 # Versi diperbarui ke v4

      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install PlatformIO Core
        run: pip install -U platformio

      - name: Compile firmware
        run: pio run -e esp32dev

      - name: Deploy firmware.bin to gh-pages branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: .pio/build/esp32dev
          # Opsi tambahan (opsional)
          # publish_branch: gh-pages # Branch tujuan (default: gh-pages)
          # user_name: 'github-actions[bot]'
          # user_email: 'github-actions[bot]@users.noreply.github.com'
          # commit_message: ${{ github.event.head_commit.message }}
          
